# Generated by Django 5.2.6 on 2025-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='backhand_type',
            field=models.CharField(blank=True, choices=[('1H', 'One-handed'), ('2H', 'Two-handed')], default='2H', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='dominant_hand',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_playing',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
