# Generated by Django 5.2.6 on 2025-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='play_intentions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_court_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_match_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
