# Generated by Django 5.2.6 on 2025-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatthread_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
