# Generated by Django 5.2.6 on 2025-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_checkin_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
